import assert from 'node:assert/strict'
import { hasHdrFillCoverage, paintHdrRasterFill } from '../src/editor/image-ops/hdr-fill'
const almost = (x: number, y: number) => assert.ok(Math.abs(x - y) < 0.00002, `${x} != ${y}`)
const p = new Float32Array([7, 3, 2, 1, 12, 4, 2, .5, 8, 1, 1, 1])
const original = p.slice()
const mask = new Uint8ClampedArray([0, 128, 0])
assert.equal(hasHdrFillCoverage(3, 1, 0, 0, 3, 1, mask), true)
assert.equal(paintHdrRasterFill(p, 3, 1, 0, 0, 3, 1, mask, '#808080'), true)
assert.deepEqual(p.slice(0, 4), original.slice(0, 4))
assert.deepEqual(p.slice(8, 12), original.slice(8, 12))
const sa = 128 / 255, da = .5
const targetA = sa + da * (1 - sa)
const linear = Math.pow((128 / 255 + .055) / 1.055, 2.4)
almost(p[4], (linear * sa + 12 * da * (1 - sa)) / targetA)
almost(p[7], targetA)
const offset = new Float32Array(12)
assert.equal(paintHdrRasterFill(offset, 3, 1, 1, 0, 3, 1, null, '#f00'), true)
assert.deepEqual([offset[0], offset[4], offset[8]], [1, 1, 0])
assert.deepEqual([offset[3], offset[7], offset[11]], [1, 1, 0])
const snapshot = offset.slice()
assert.equal(hasHdrFillCoverage(3, 1, 0, 0, 3, 1, new Uint8ClampedArray(3)), false)
assert.equal(paintHdrRasterFill(offset, 3, 1, 0, 0, 3, 1, new Uint8ClampedArray(3), '#fff'), false)
assert.deepEqual(offset, snapshot)
assert.throws(() => paintHdrRasterFill(offset, 3, 1, 0, 0, 3, 1, null, 'red'), /hexadecimal/)
assert.throws(() => paintHdrRasterFill(offset, 2, 1, 0, 0, 3, 1, null, '#fff'), /dimensions/)
console.log('Scene-linear HDR Fill: highlights, feathered alpha, offsets and no-op preserve precision')
